/* BootScene.js — the first thing anybody sees, in three dimensions.
   ===========================================================================
   The loading screen used to be CSS and SVG: a gradient sky, a flat green
   hill and a drawn fox peering over a sign. It read as a placeholder,
   which is a bad thing for the one screen every player looks at before
   they have decided whether to care about the game.

   This is the same picture built for real — a fox sitting on a bank at
   the edge of a pool, under trees, with leaves coming down — rendered by
   the same renderer, with the same materials, the same water shader and
   the same tone mapping as the game itself. That last part is the point:
   the loading screen is not a picture OF the game, it is a small piece
   of the game, so the first impression and the second one agree.

   WHY THIS IS AFFORDABLE. Everything here is generated by the same
   builders the world uses, and the whole scene is five trees, a bank, a
   pool and one animal — tens of milliseconds, against the several
   seconds of world generation it is covering. It is built before the
   world starts and disposed the moment the world is ready, so it costs
   nothing once the game is running.

   THE COMPOSITION, which is the part that has to be got right rather
   than merely coded:

     The fox sits at the third, facing across the water, small in frame.
     Something small in a big quiet place is the whole tone of the game;
     a fox filling the screen would be a character select.

     The camera drifts. A slow arc, a couple of metres over several
     seconds, with the focus staying on the fox. Movement is what
     separates a render from a screenshot.

     The light is low and warm and comes from behind the trees, so the
     canopy is rimmed and the water carries a long highlight. Flat
     overhead light makes generated geometry look like untextured
     geometry, which it is.
*/

import * as THREE from '../../lib/three.module.js?v=1790100127';
import { MeshBuilder, quad, blob, tube } from '../art/Geo.js?v=1790100127';
import { MATS, makeWaterMaterial, updateWind } from '../art/Materials.js?v=1790100127';
import { buildTree } from '../art/TreeGen.js?v=1790100127';
import { buildReeds, buildGrassTuft, buildRock, buildFern } from '../art/PlantGen.js?v=1790100127';
import { buildAnimal } from '../art/AnimalArt.js?v=1790100127';
import { poseAnimal } from '../game/Anim.js?v=1790100127';
import { SKY, WATER, GROUND, mixHex, tweak } from '../art/Palette.js?v=1790100127';
import { makeRng, clamp, clamp01, lerp, TAU } from '../core/Util.js?v=1790100127';

const WATER_Y = 0;
const BANK_Y = 0.42;
/* BIG ENOUGH TO BE A POOL. Three and a half metres is a puddle, and in a
   wide shot it read as one: a grey coin dropped on a lawn, with the lawn
   as the subject. Five and a half puts water across the bottom half of
   the frame, which is what a game about fishing ought to be showing. */
const POOL_R = 5.5;

/**
 * THE SHORELINE, which is not a circle.
 *
 * A pool of constant radius is a stamped hole — the eye reads the perfect
 * arc instantly and everything inside it becomes a decal. Two low
 * harmonics are enough to break that: the bank comes in and out, the
 * reeds gather in the bays, and nobody can see the rule.
 *
 * The SAME function has to drive the ground height and the water mesh, or
 * the surface and the bed disagree and the water spills over one side of
 * its own basin.
 */
function shoreR(a) {
  return POOL_R * (1 + Math.sin(a * 3 + 0.7) * 0.15 + Math.sin(a * 5 - 2.1) * 0.08);
}

/**
 * WHERE THE LIGHT COMES FROM, stated once.
 *
 * It is low, warm and beyond the far treeline, which rims the wood and —
 * because the water material now takes this same vector — lays the sun's
 * reflection in a long path down the pool towards the lens. Those two
 * things have to be the same number. When the key was over here and the
 * water shader's sparkle was hard-coded over there, the pool had no
 * highlight on it at all and rendered as a sheet of grey.
 */
const SUN = [-5.5, 2.4, -17];

/** the colour the distance goes to: sky, fog and haze all agree on it, so
    the far ground melts into the horizon instead of ending in a white
    stripe under the trees */
const HAZE = 0xdcd0ac;

export class BootScene {
  /**
   * @param canvas   a canvas of its own, layered under the sign
   * @param renderer optional: the game's renderer, if it exists yet
   */
  constructor(canvas) {
    this.canvas = canvas;
    this.ok = false;
    try {
      this.renderer = new THREE.WebGLRenderer({
        canvas, antialias: true, alpha: false, powerPreference: 'high-performance',
      });
    } catch (e) {
      /* NO GPU, NO PROBLEM. The CSS scene behind this stays visible and
         the player gets the old loading screen rather than a black hole
         where the loading screen used to be. */
      console.warn('[boot] no WebGL for the loading scene', e);
      return;
    }
    this.renderer.setPixelRatio(Math.min(2, globalThis.devicePixelRatio || 1));
    this.renderer.setSize(innerWidth, innerHeight, false);
    this.renderer.outputColorSpace = THREE.SRGBColorSpace;
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.18;

    this.scene = new THREE.Scene();
    /* A WIDER LENS THAN A GAME CAMERA. At 38 degrees, a tree tall enough
       to read as a tree has to stand thirty metres back before its crown
       fits in the frame, and thirty metres of empty lawn between the pool
       and the wood is not a wood, it is a golf course. Fifty degrees puts
       the canopy in the top of the picture from fourteen metres and gives
       the shot the slight wide-angle openness that establishing shots
       have and gameplay cameras do not. */
    this.camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 220);
    this.t = 0;
    this.r = makeRng(0xb007);

    this._sky();
    this._light();
    this._ground();
    this._water();
    this._trees();
    this._fox();
    this._leaves();

    this.ok = true;
    addEventListener('resize', this._onResize = () => this.resize());
  }

  resize() {
    if (!this.ok) return;
    this.camera.aspect = innerWidth / innerHeight;
    this.camera.updateProjectionMatrix();
    this.renderer.setSize(innerWidth, innerHeight, false);
  }

  /* ====================================================================== */

  _sky() {
    /* A GRADIENT DOME, not a flat clear colour. The horizon has to be
       paler than the zenith or the treeline has nothing to sit against,
       and fog alone cannot do it because there is no distance here. */
    const b = new MeshBuilder();
    const R = 120, RINGS = 8, SEG = 24;
    for (let j = 0; j < RINGS; j++) {
      const t0 = j / RINGS, t1 = (j + 1) / RINGS;
      const y0 = Math.cos(t0 * Math.PI * 0.55), y1 = Math.cos(t1 * Math.PI * 0.55);
      const r0 = Math.sin(t0 * Math.PI * 0.55), r1 = Math.sin(t1 * Math.PI * 0.55);
      for (let i = 0; i < SEG; i++) {
        const a0 = (i / SEG) * TAU, a1 = ((i + 1) / SEG) * TAU;
        /* WARM AT THE HORIZON, COOL OVERHEAD — and the first version had
           it exactly the other way up, because `t` runs from the zenith
           down. The warmth is held back to the bottom third rather than
           smeared over the whole dome: a gradient that starts warming at
           the top is a sunset poster, one that only warms near the
           treeline is late afternoon. */
        const c0 = mixHex(SKY.zenith, HAZE, Math.pow(clamp01((t0 - 0.38) * 1.75), 1.4));
        b.color(c0, 0.01);
        const P = (a, rr, yy) => [Math.cos(a) * rr * R, yy * R * 0.7, Math.sin(a) * rr * R];
        const p0 = P(a0, r1, y1), p1 = P(a1, r1, y1), p2 = P(a1, r0, y0), p3 = P(a0, r0, y0);
        /* OUTWARD IS RADIAL, and it matters twice over. `outward` sets
           which way the FRONT of the face points, and the dome's material
           is BackSide so the player is meant to see its inside — which
           means the fronts have to point away from the middle. The first
           version passed [0,-1,0], which pointed them inward; BackSide
           then culled the lot and the loading screen rendered its sky as
           pure black. */
        const out = [(p0[0] + p2[0]) / 2, (p0[1] + p2[1]) / 2, (p0[2] + p2[2]) / 2];
        quad(b, p0, p1, p2, p3, null, out);
      }
    }
    const m = new THREE.Mesh(b.build({ flat: false }), new THREE.MeshBasicMaterial({
      vertexColors: true, side: THREE.BackSide, fog: false, depthWrite: false,
    }));
    m.renderOrder = -10;
    this.scene.add(m);
    /* ENOUGH TO SEPARATE THE RANKS, NOT ENOUGH TO ERASE THEM. At 0.019
       the deep wood came back the colour of paper: forty metres of that
       is nearly half haze, and a treeline you cannot see is not depth,
       it is absence. */
    this.scene.fog = new THREE.FogExp2(HAZE, 0.0085);
  }

  _light() {
    /* LOW, WARM, AND FROM BEHIND. The key comes through the trees at a
       shallow angle so the canopy is rimmed and the water carries a long
       highlight; a lamp over the camera's shoulder lights generated
       geometry evenly and evenly-lit generated geometry looks like
       untextured geometry. */
    /* LOWER AND WARMER THAN THE FIRST PASS. A key at three and a hemi at
       one and a sixth adds up to flat noon: everything is lit, nothing is
       modelled, and the render came back looking like a product shot. The
       key is stronger relative to the ambient now and sits closer to the
       horizon, which is what puts a rim on the far trees and a long
       highlight down the pool. */
    const key = new THREE.DirectionalLight(0xffd79a, 3.4);
    key.position.set(SUN[0], SUN[1], SUN[2]);
    this.scene.add(key);

    /* the cool bounce out of the sky, which keeps the shadow side from
       going to mud — but only just enough to do that */
    this.scene.add(new THREE.HemisphereLight(0xa9c9e8, 0x44532f, 0.72));

    /* a small warm fill from the water, so the fox's underside is not
       a silhouette */
    const bounce = new THREE.DirectionalLight(0xffd8a0, 0.5);
    bounce.position.set(4, -2, 6);
    this.scene.add(bounce);
  }

  /**
   * THE GROUND, as a heightfield rather than as rings.
   *
   * The first version built the bank as concentric rings of quads with
   * the height driven by the radius, and it came out as a terraced pit —
   * a quarry with a pond at the bottom. Two things were wrong and both
   * are worth stating: a ring grid makes every height step a visible
   * contour line, and a height that depends only on distance from the
   * middle can only ever produce a bowl.
   *
   * So it is a plain grid sampled from a height function with some noise
   * in it. The bowl is still there — it has to be, there is a pool in
   * the middle — but it is one term among several instead of the whole
   * shape.
   */
  _ground() {
    const b = new MeshBuilder();
    const r = this.r;

    const H = (x, z) => {
      const d = Math.hypot(x, z);
      /* the bed of the pool, then the bank climbing away from it */
      /* THE LAND BEYOND THE BANK IS NEARLY LEVEL. It used to climb two and
         a half metres over fifteen, which sounds gentle and is not: it
         lifted the wood three metres above the pool, and a treeline
         standing three metres up at fifteen metres out has its crowns
         above the top of any lens you can point at the water. Every
         render came back as trunks. Eighty-five centimetres of rise is
         still a valley and leaves room for sky. */
      const R = shoreR(Math.atan2(z, x));
      const bowl = d < R
        ? -0.95 * (1 - Math.pow(d / R, 1.7))            // always under water
        : BANK_Y * Math.min(1, (d - R) / 1.3)
        + Math.pow(clamp01((d - R) / 15), 1.25) * 0.85;
      /* and the ground it is cut into: two scales of roll, so the far
         bank has shape and the near one is not a ramp */
      const roll = Math.sin(x * 0.19 + 1.3) * 0.34 + Math.sin(z * 0.23) * 0.28
        + Math.sin((x + z) * 0.52) * 0.10;
      const away = clamp01((d - R) / 4);
      return bowl + roll * away;
    };
    this._H = H;

    /* WIDE ENOUGH TO REACH THE HAZE. A forty-six metre field ends
       twenty-three metres out, which is nearer than the far rank of
       trees — so the deep wood stood on nothing and there was a bare
       strip of sky between the ground's edge and the horizon. Eighty
       metres puts the edge far enough back that the fog has closed over
       it before it arrives. */
    const N = 80, SPAN = 80;
    for (let j = 0; j < N; j++) {
      for (let i = 0; i < N; i++) {
        const x0 = -SPAN / 2 + (i / N) * SPAN, x1 = -SPAN / 2 + ((i + 1) / N) * SPAN;
        const z0 = -SPAN / 2 + (j / N) * SPAN, z1 = -SPAN / 2 + ((j + 1) / N) * SPAN;
        const mx = (x0 + x1) / 2, mz = (z0 + z1) / 2;
        const d = Math.hypot(mx, mz);
        const R = shoreR(Math.atan2(mz, mx));
        /* wet sand at the margin, grass beyond it, silt under the water */
        /* PATCHY AT A SCALE YOU CAN SEE. Per-cell jitter is texture; it
           does nothing about the fact that thirty square metres of
           meadow was one flat green. Two slow waves, six and eleven
           metres across, drift the grass between a dry yellow and a
           deep shaded green, and that is what turns the lawn into
           ground. */
        const patch = Math.sin(mx * 0.17 + 0.9) * Math.sin(mz * 0.21 - 0.4) * 0.5
          + Math.sin((mx - mz) * 0.09 + 2.2) * 0.5;
        const grass = mixHex(mixHex(0x53682f, GROUND.grass, clamp01(patch * 0.5 + 0.5)),
          0x8d8f47, clamp01(patch) * 0.30);
        const col = d < R ? 0x6a5c42
          : mixHex(0x8a7854, grass, clamp01((d - R) / 2.6));
        /* A WHISPER OF VARIATION, NOT A CHESSBOARD. Eight per cent of
           lightness per cell on a regular grid is not texture, it is a
           checkerboard, and the first render read as lino. Two per cent
           with a little hue jitter gives the surface life without ever
           resolving into squares. */
        b.color(tweak(col, { l: r.range(0.98, 1.02) }), 0.016, r);
        quad(b,
          [x0, H(x0, z0), z0], [x1, H(x1, z0), z0],
          [x1, H(x1, z1), z1], [x0, H(x0, z1), z1], null, [0, 1, 0]);
      }
    }
    this.scene.add(new THREE.Mesh(b.build({ flat: false }), MATS.solid));

    /* --- the margin ------------------------------------------------------
       Stones and tufts on the bank, reeds standing in the shallows. Both
       are kept OFF the near side between the fox and the water, because
       that is the sightline the whole composition is built on and a reed
       bed across it is a hedge in front of the subject. */
    const dress = new MeshBuilder();
    /* the corridor the shot is built on: from the lens on the near bank,
       past the fox, across the water. Nothing is planted in it. */
    const clearOfView = (x, z) => !(z > 0.2 && x > -1.4 && x < 2.6);

    /* OUT TO THE TREELINE, NOT JUST ROUND THE RIM. Six metres of dressing
       round a three-metre pool left a bare lawn between the margin and
       the wood, which is the largest single area of the picture and was
       the emptiest. The density falls off with distance so the eye still
       reads the rim as the busy part. */
    for (let i = 0; i < 210; i++) {
      const a = r.range(0, TAU), d = shoreR(a) + 0.2 + Math.pow(r.range(0, 1), 0.75) * 16;
      const x = Math.cos(a) * d, z = Math.sin(a) * d;
      if (!clearOfView(x, z)) continue;
      const sub = new MeshBuilder();
      if (r.chance(0.26)) buildRock(sub, { seed: r.seed(), size: r.range(0.14, 0.42), lod: 0, mossy: 0.55 });
      else if (r.chance(0.55)) buildGrassTuft(sub, { seed: r.seed(), size: r.range(0.22, 0.58), lod: 0 });
      else buildFern(sub, { seed: r.seed(), size: r.range(0.3, 0.68), lod: 0 });
      dress.append(sub, new THREE.Matrix4().compose(
        new THREE.Vector3(x, H(x, z) - 0.03, z),
        new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), r.range(0, TAU)),
        new THREE.Vector3(1, 1, 1)));
    }

    /* REEDS GATHER IN THE BAYS. They stand in the shallows all the way
       round, but the shoreline is not a circle any more, so following it
       puts them thickest where the bank curves in — which is where reeds
       actually grow, and is the cheapest possible way of making a
       generated edge look like it grew rather than like it was drawn. */
    for (let i = 0; i < 34; i++) {
      const a = r.range(0, TAU), R = shoreR(a), d = r.range(R - 1.0, R + 0.3);
      const x = Math.cos(a) * d, z = Math.sin(a) * d;
      if (!clearOfView(x, z)) continue;
      const sub = new MeshBuilder();
      buildReeds(sub, { seed: r.seed(), size: r.range(0.5, 0.95), lod: 0 });
      dress.append(sub, new THREE.Matrix4().compose(
        new THREE.Vector3(x, WATER_Y - 0.12, z),
        new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), r.range(0, TAU)),
        new THREE.Vector3(1, 1, 1)));
    }
    /* --- THE FOREGROUND ---------------------------------------------------
       A few big tufts close to the lens, in the bottom corners only. A
       picture with nothing within six metres of the camera has no depth
       to it — the eye has nothing near to measure the distance against,
       and the whole shot flattens into a backdrop. These are deliberately
       oversized and deliberately cropped by the frame: they are not
       scenery, they are the near edge of the world. */
    const near = new MeshBuilder();
    for (let i = 0; i < 26; i++) {
      /* an arc behind and beside the lens, skipping the corridor it
         looks down */
      const a = r.range(0, TAU);
      const d = r.range(8.5, 13.5);
      const x = Math.cos(a) * d, z = Math.sin(a) * d;
      if (z < 6.0) continue;                 // only the near bank
      if (x > -1.8 && x < 3.2) continue;     // never across the sightline
      const sub = new MeshBuilder();
      if (r.chance(0.55)) buildGrassTuft(sub, { seed: r.seed(), size: r.range(0.7, 1.25), lod: 0 });
      else buildFern(sub, { seed: r.seed(), size: r.range(0.8, 1.4), lod: 0 });
      near.append(sub, new THREE.Matrix4().compose(
        new THREE.Vector3(x, H(x, z) - 0.05, z),
        new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), r.range(0, TAU)),
        new THREE.Vector3(1, 1, 1)));
    }
    this.scene.add(new THREE.Mesh(near.build({ flat: false }), MATS.foliage));

    /* --- WHAT IS IN THE POOL ----------------------------------------------
       An unbroken sheet of water is the one thing that always looks
       generated, however good the shader is, because real water always
       has something sitting in it. A fallen alder half in the shallows,
       a few boulders breaking the surface, and lily pads — which are also
       the game's own signal for "fish live here", so the loading screen
       is quietly showing the player what the game is about. Kept to the
       far half, out of the corridor the shot looks down. */
    const inPool = new MeshBuilder();

    /* the log: a tapered trunk lying across the far shallows, one end on
       the bank and the other under */
    {
      const a = 2.35;                       // far left of the pool
      const R = shoreR(a);
      const bx = Math.cos(a) * (R + 0.5), bz = Math.sin(a) * (R + 0.5);
      const sub = new MeshBuilder();
      sub.color(0x6b5741, 0.05, r);
      tube(sub, {
        pts: [[0, 0, 0], [1.2, -0.24, 0.42], [2.4, -0.48, 0.86], [3.4, -0.66, 1.22]],
        radius: t => 0.23 - t * 0.07, radial: 8,
        bump: (t, a) => 1 + Math.sin(a * 5 + t * 9) * 0.06,
      });
      inPool.append(sub, new THREE.Matrix4().makeTranslation(bx, H(bx, bz) + 0.14, bz));
    }

    /* boulders standing proud of the surface */
    for (let i = 0; i < 5; i++) {
      const a = r.range(1.5, 4.2), d = shoreR(a) * r.range(0.45, 0.86);
      const x = Math.cos(a) * d, z = Math.sin(a) * d;
      const sub = new MeshBuilder();
      buildRock(sub, { seed: r.seed(), size: r.range(0.26, 0.55), lod: 0, mossy: 0.8 });
      inPool.append(sub, new THREE.Matrix4().makeTranslation(x, WATER_Y - r.range(0.06, 0.22), z));
    }
    this.scene.add(new THREE.Mesh(inPool.build({ flat: false }), MATS.solid));

    /* the pads, which float ON the surface and so are built separately and
       drawn after the water */
    const pads = new MeshBuilder();
    for (let i = 0; i < 17; i++) {
      const a = r.range(1.1, 4.6), d = shoreR(a) * r.range(0.35, 0.90);
      const x = Math.cos(a) * d, z = Math.sin(a) * d;
      const rad = r.range(0.17, 0.33);
      pads.color(tweak(0x4e7c3a, { l: r.range(0.85, 1.15) }), 0.05, r);
      /* a disc with a notch, which is the whole silhouette of a lily pad */
      const cut = r.range(0, TAU), SEGP = 11;
      const c = pads.vert(x, WATER_Y + 0.035, z, 0);
      const ring = [];
      for (let k = 0; k <= SEGP; k++) {
        const aa = cut + 0.42 + (k / SEGP) * (TAU - 0.84);
        ring.push(pads.vert(x + Math.cos(aa) * rad, WATER_Y + 0.035, z + Math.sin(aa) * rad, 0));
      }
      for (let k = 0; k < SEGP; k++) pads.tri(c, ring[k + 1], ring[k]);
    }
    const padMesh = new THREE.Mesh(pads.build({ flat: false }), MATS.foliage);
    padMesh.renderOrder = 3;
    this.scene.add(padMesh);

    this.scene.add(new THREE.Mesh(dress.build({ flat: false }), MATS.foliage));
  }

  _water() {
    /* the same shader the lakes use, so the loading screen and the game
       agree about what water looks like */
    const b = new MeshBuilder();
    const SEG = 72, RINGS = 10;
    /* the surface follows the SAME shoreline the bed is cut to, a
       hair inside it so the water never climbs its own bank */
    const edge = a => shoreR(a) * 0.985;
    for (let j = 0; j < RINGS; j++) {
      const f0 = j / RINGS, f1 = (j + 1) / RINGS;
      for (let i = 0; i < SEG; i++) {
        const a0 = (i / SEG) * TAU, a1 = ((i + 1) / SEG) * TAU;
        /* the red channel is depth, which the water shader reads: 1 in
           the middle of the pool, 0 at the margin where the foam is.
           It is squared so the shallow, clear, foamy band hugs the bank
           instead of reaching a third of the way across the pool. */
        const dep = f => clamp01(1 - f) ** 0.55;
        const p = (f, a) => [Math.cos(a) * edge(a) * f, WATER_Y, Math.sin(a) * edge(a) * f];
        quadDepth(b, p(f0, a0), p(f1, a0), p(f1, a1), p(f0, a1),
          dep(f0), dep(f1), dep(f1), dep(f0));
      }
    }
    /* A DEEPER, GREENER PAIR THAN THE OPEN LAKES USE. The lake colours are
       tuned for water you are standing in the middle of under an open sky;
       this is a woodland pool with a canopy over half of it, and given the
       lake pair it came out the pale grey of wet concrete. */
    /* THE THIRD COLOUR IS WHAT THE SURFACE REFLECTS AT A GRAZING ANGLE,
       and for a pool with a wood round it that is the wood. Handing it
       the sky colour — which is what the open lakes correctly use — made
       the pool pale grey from every angle the camera can actually see it
       from, because looking across water is nearly all grazing angle.
       Water takes its colour from what is standing over it. */
    this.waterMat = makeWaterMaterial(0x5d8f78, 0x14312b, 0x40604e, SUN);
    const m = new THREE.Mesh(b.build({ flat: false }), this.waterMat);
    m.renderOrder = 2;
    this.scene.add(m);
  }

  _trees() {
    const r = this.r;
    const b = new MeshBuilder();
    /*
     * THE TREELINE, placed in WORLD COORDINATES on the far side.
     *
     * The first version placed them on a polar arc, and the arc it chose
     * put most of them behind the camera: the render came back as a pond
     * in an empty field. The camera looks along -Z from the near bank, so
     * "behind the water" means negative Z, and saying that directly is
     * both clearer and impossible to get backwards.
     *
     * Two ranks: a close one that reads as individual trees, and a far
     * one that closes the horizon. Nothing on the near side — the ground
     * between the lens and the fox stays open or the shot is a hedge.
     */
    const kinds = ['oak', 'birch', 'pine', 'willow', 'alder'];
    const H = this._H || (() => 0);
    const plant = (x, z, scale) => {
      const sub = new MeshBuilder();
      buildTree(sub, {
        species: r.pick(kinds), seed: r.seed(), lod: 0,
        scale, mossy: r.range(0.2, 0.7), autumn: r.range(0, 0.45),
      });
      b.append(sub, new THREE.Matrix4().compose(
        new THREE.Vector3(x, H(x, z) - 0.12, z),
        new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), r.range(0, TAU)),
        new THREE.Vector3(1, 1, 1)));
    };

    /* FAR ENOUGH BACK TO BE TREES. At five metres behind the pool a
       fifteen-metre oak is a trunk filling the frame — the first render
       came back as a wall of bark with the pool nowhere in it. They
       start beyond nine metres, which on a 38 degree lens is where a
       tree reads as a whole tree. */
    /* THE SCALES ARE SMALL BECAUSE THE TREES ARE ENORMOUS. A `scale: 1`
       oak in this game is twenty-five metres and a pine twenty-seven —
       forest giants, which is right for a world you walk through and
       hopeless for a picture with a three-metre pool in it. Three
       successive renders came back as cropped trunks while the scales
       were being guessed at; they are measured now (probe_treesize.mjs),
       and a third of full size is an eight-metre tree, which is a tree
       whose whole shape fits above a pond. */
    for (let i = 0; i < 13; i++) {
      const x = lerp(-15, 15, i / 12) + r.range(-1.6, 1.6);
      const z = -r.range(16, 24);
      plant(x, z, r.range(0.30, 0.42));
    }
    /* and a deeper rank to close the horizon */
    for (let i = 0; i < 19; i++) {
      const x = lerp(-34, 34, i / 18) + r.range(-2.6, 2.6);
      const z = -r.range(28, 44);
      plant(x, z, r.range(0.38, 0.58));
    }
    /* NOTHING NEAR THE LENS. Two "framing" trees on the near bank were
       simply two trunks across the picture: at that range they are not a
       frame, they are an obstruction. */

    this.scene.add(new THREE.Mesh(b.build({ flat: false }), MATS.foliage));
  }

  _fox() {
    /* SMALL, AND AT THE THIRD. A fox filling the frame is a character
       select; a fox this size in a place this size is the game.
       It sits on the near bank looking across the water — so it is
       between the lens and the subject, which is what makes the subject
       the place rather than the animal. */
    this.fox = buildAnimal('fox', { seed: 7 });
    /* CLOSE TO THE CAMERA'S AXIS, not merely off to one side. At four
       metres, a metre and a half of lateral offset is already twenty
       degrees; the first staging put the fox three and a half metres off
       the axis and it went straight out of the left of the frame. */
    const fx = 0.1, fz = shoreR(Math.atan2(1, 0)) + 0.55;
    this.foxAt = new THREE.Vector3(fx, (this._H ? this._H(fx, fz) : BANK_Y) + 0.02, fz);
    this.fox.root.position.copy(this.foxAt);
    /* facing the water, turned a little towards the lens so the render
       is a fox and not the back of one */
    /* turned TOWARDS the lens, which is off to its right — the sign was
       the other way round and it showed the camera the back of a fox */
    this.fox.root.rotation.y = Math.atan2(-fx, -fz) - 0.55;
    this.scene.add(this.fox.root);
  }

  _leaves() {
    /* FALLING LEAVES, which are most of what makes a still scene feel
       alive — and cheap: one small mesh each, drifting and turning. */
    const r = this.r;
    this.leaves = [];
    const cols = [0xd8a24c, 0xc4762e, 0xe0c060, 0x9aa848];
    for (let i = 0; i < 26; i++) {
      const b = new MeshBuilder();
      b.color(tweak(cols[i % cols.length], { l: r.range(0.85, 1.15) }), 0.06, r);
      const w = r.range(0.035, 0.075);
      quad(b, [-w, 0, -w * 1.5], [w, 0, -w * 1.5], [w * 0.7, 0, w * 1.5], [-w * 0.7, 0, w * 1.5],
        null, [0, 1, 0]);
      const m = new THREE.Mesh(b.build({ flat: false }), MATS.foliage);
      m.position.set(r.range(-9, 9), r.range(1, 8), r.range(-4, 9));
      this.scene.add(m);
      this.leaves.push({
        m,
        fall: r.range(0.16, 0.42),
        sway: r.range(0.5, 1.5),
        phase: r.range(0, TAU),
        spin: r.range(-1.6, 1.6),
      });
    }
  }

  /* ====================================================================== */

  update(dt) {
    if (!this.ok) return;
    this.t += dt;
    const t = this.t;

    /* the water shader and every swaying plant read the shared wind clock */
    updateWind(t, 0.35 + Math.sin(t * 0.21) * 0.25);

    /* --- THE CAMERA DRIFTS ------------------------------------------------
       A slow arc round the fox with a gentle rise, easing at both ends of
       a long cycle so it never appears to be on rails. Movement is what
       separates a render from a screenshot. */
    /* BEHIND AND ABOVE THE FOX, LOOKING ACROSS THE WATER at the
       treeline. The first version orbited the fox, which swung the
       camera round behind the trees and out into an empty field on half
       its cycle; the shot is fixed in its essentials now and only
       breathes — a slow lateral slide, a slight rise, a little push in.
       An arc is only interesting if everything is interesting from every
       angle, and a small set is not. */
    /* HIGH ENOUGH TO SEE THE WATER. At two metres, looking level at a
       point thirteen metres away, the pool sits below the bottom of the
       frame and the picture is trees and grass — which is exactly what
       the first render came back as. Three and a bit metres, pitched
       down about seventeen degrees at the far bank, puts the pool in the
       middle of the frame with the treeline behind it and the fox in the
       near right. */
    /* NEARLY LEVEL, AND LOW. Three metres up pitched seventeen degrees
       down is a surveillance camera: it fills the frame with the ground
       and crops the trees at the knees, which is what the render came
       back as. A lens a bit over a metre off the bank, looking very
       slightly down at a point nine metres out, puts the pool across the
       lower third, the far bank and the wood in the middle, and sky
       along the top — and it is roughly the fox's own eyeline, which is
       the reason the picture feels like somewhere rather than like a
       plan of somewhere. */
    const sway = Math.sin(t * 0.085);
    const push = Math.sin(t * 0.063 + 1.1);
    const cx = 2.2 + sway * 0.55, cz = 10.6 + push * 0.45;
    /* HEIGHT ABOVE THE BANK, NOT ABOVE ZERO. The bank at the lens is a
       metre and a third up, so a camera at y = 1.15 was inside the hill:
       the bottom half of the render was the black backside of the ground
       it was buried in. */
    const eye = (this._H ? this._H(cx, cz) : 0) + 1.05 + Math.sin(t * 0.048) * 0.09;
    this.camera.position.set(cx, eye, cz);
    this._lookAt = [
      -0.2 + sway * 0.30,
      1.50 + Math.sin(t * 0.07) * 0.06,
      -10.0,
    ];
    this.camera.lookAt(this._lookAt[0], this._lookAt[1], this._lookAt[2]);

    /* --- the fox breathes, blinks and looks about ------------------------ */
    if (this.fox) {
      poseAnimal(this.fox, {
        t, dt, speed: 0, moving: false, grounded: true,
        yaw: this.fox.root.rotation.y,
        /* it watches the water, then glances up, on a long slow cycle */
        lookAt: [
          Math.sin(t * 0.17) * 2.5,
          BANK_Y + 0.35 + Math.max(0, Math.sin(t * 0.11 - 1)) * 1.4,
          -2.5 + Math.cos(t * 0.13) * 1.5,
        ],
      });
    }

    /* --- the leaves ------------------------------------------------------ */
    for (const L of this.leaves) {
      L.m.position.y -= L.fall * dt;
      L.m.position.x += Math.sin(t * L.sway + L.phase) * 0.5 * dt;
      L.m.position.z += Math.cos(t * L.sway * 0.7 + L.phase) * 0.35 * dt;
      L.m.rotation.x += L.spin * dt * 0.6;
      L.m.rotation.z += L.spin * dt;
      if (L.m.position.y < WATER_Y - 0.2) {
        /* back to the canopy, somewhere else */
        L.m.position.set(this.r.range(-9, 9), this.r.range(6, 9), this.r.range(-4, 9));
      }
    }

    this.renderer.render(this.scene, this.camera);
  }

  dispose() {
    removeEventListener('resize', this._onResize);
    if (!this.ok) return;
    this.scene.traverse(o => {
      if (o.isMesh) {
        o.geometry?.dispose();
        if (o.material && o.material !== MATS.solid && o.material !== MATS.foliage) {
          o.material.dispose?.();
        }
      }
    });
    this.renderer.dispose();
    this.ok = false;
  }
}

/* ------------------------------------------------------------------------- */

/**
 * A quad whose four vertices carry a per-corner DEPTH in the red channel,
 * which is what the water shader reads to decide colour and clarity. The
 * builder's own `quad` writes one colour for the whole face, so the
 * shallows and the middle of the pool would come out identical.
 *
 * The depth is pushed as a LINEAR colour triple directly, not through
 * `b.color()`: that runs an sRGB→linear table, which is right for
 * anything anybody looks at and wrong for a channel being used to carry
 * a number the shader will read back.
 */
function quadDepth(b, p0, p1, p2, p3, d0, d1, d2, d3) {
  const put = (p, d) => b.vert(p[0], p[1], p[2], 0, [clamp01(d), 0, 0]);
  const a = put(p0, d0), c = put(p1, d1), e = put(p2, d2), f = put(p3, d3);
  /* WOUND SO THE FACE LOOKS UP. The first version wound these the other
     way; the water material is a Lambert, Lambert is FrontSide, and a
     surface whose normal points at the bed is a surface nobody can see.
     The loading screen rendered a brown empty bowl for three rounds
     because of it, and it is exactly the kind of fault that no amount of
     reading the code finds and one look at the picture finds instantly. */
  b.tri(a, e, c);
  b.tri(a, f, e);
}
